version: '3'

services:
  apache:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
         - http_proxy
         - https_proxy
         - no_proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./code/:/app
    args:
       - http_proxy
       - https_proxy
       - no_proxy
