version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
         - http_proxy
         - https_proxy
         - no_proxy
    ports:
      - 8888:8888
    volumes:
      - ./notebook:/home/jovyan/work/
    environment:
      - GRANT_SUDO="yes"
